### ISSUE TITLE
Add Monday Punday functionality

### ISSUE THREAD

**Issue by ohhellojackie** [ecalfonso/discord-bot#1]
Post the latest Monday Punday every Monday (if a new page has been detected):
http://mondaypunday.com/

Ideally have the bot detect if the newer page exists every Monday from the last known page. (E.g. This week was http://mondaypunday.com/387, check next week for 388.) If none exists, check each day for a new page. If that's too many calls, make a sad error message.

**Comment by ecalfonso** [comment]
Should be added in https://github.com/ecalfonso/discord-bot/commit/0f89ff35cd3109a0f05b525002c25f684ca6fc6d

We'll see what happens 6/4/2018, but I'm pretty sure it'll work
